name: Auto Create Pull Request

on:
  workflow_run:
    workflows: ["Combined Continuous Integration"]
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create Pull Request
      run: gh pr create -B main -H ${{ github.head_ref || github.ref_name }}  --title "Merge branch '${{ github.head_ref || github.ref_name }}' into main" --body 'Automatically created by GitHub action'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
